default:
  background-color: white
  text-color: black
  message-duration: 5
  shadowed: false
  see-through: false
  billboard-style: CENTER
  offsets:
    x: 0.0
    y: 0.5
    z: 0.0
  scale: 1.0

channels:
  global:
    background-color: blue
    message-duration: 10